# Generated by Django 5.1.5 on 2025-05-01 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=4)),
                ('stock_name', models.TextField()),
                ('stock_time', models.DateTimeField(default=datetime.date.today)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
